#!/usr/bin/env php
<?php
    /**
    * exec is the CLI for the eventual Framework
    **/

    // Define the app constants
    defined('EVENTUAL_ROOT') || define('EVENTUAL_ROOT', str_replace('\\', DIRECTORY_SEPARATOR, realpath(dirname(dirname(__FILE__))).DIRECTORY_SEPARATOR));

    // Allow access to STDIN from fcgi
    defined('STDIN') || define('STDIN', fopen('php://stdin', 'r'));

    // Allow access to STDOUT from fcgi
    // defined('STDOUT') || define('STDOUT', fopen('php://stdout', 'w'));

    // Include the base utilities class and register the autoloader
    require_once(EVENTUAL_ROOT.'icatalyst'.DIRECTORY_SEPARATOR.'eventual'.DIRECTORY_SEPARATOR.'Utilities.php');
    spl_autoload_register('\icatalyst\eventual\Utilities::loadClass');

    // Create the console bootstrap, if we are running from phpunit, use the test context
    $loBootstrap = new \icatalyst\eventual\console\Bootstrap(strpos(strtolower($_SERVER['PHP_SELF']), 'phpunit.php') >= 0 ?
         new \icatalyst\eventual\console\TestContext() :
         null);
    $loBootstrap->run();
?>